version: "3"

services:
  bot:
    container_name: talones-bot
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - MODE=${MODE}
    volumes:
      - "/home/andres/bot/storage:/storage"
    restart: always
